// Automatically included in './src/main.js'

import './app'
import './chartist'
import './webfontloader'
import './vue-meta'
import './axios'
import './vue-cookies'
import './vuelidate'
import './vue-toast-notification'
import './vue-confirm-dialog'
import './vue-moment'
